---
- name: Generate dynamic Ansible inventory
  hosts: all
  gather_facts: yes
  tasks:
    - name: Write dynamic hosts file locally
      template:
        src: templates/hosts.j2
        dest: ./hosts  # in your working directory
      run_once: true
